language: java
jdk:
  - openjdk11

# Install necessary services
services:
  - xvfb

# Install dependencies
before_install:
  - sudo apt-get update
  - sudo apt-get install -y xvfb

# Specify the build and test script
script:
  - mvn clean test

# Define cache to speed up build process
cache:
  directories:
    - $HOME/.m2

# Notifications
notifications:
  email:
    recipients:
      - rohit.sinha@lab49.com
    on_success: always
    on_failure: always
